apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: containers
    image: tmkube/app
    ports:
    - containerPort: 8080
