apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-file
spec:
  containers:
  - name: container-file
    image: tmkube/init
    env:
    - name: cm-file
      valueFrom:
        configMapKeyRef:
          key: a.txt
          name: cm-file
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-sec-file
spec:
  containers:
  - name: container-file
    image: tmkube/init
    env:
    - name: sec-file
      valueFrom:
        secretKeyRef:
          key: b.txt
          name: sec-file
