apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-1
spec:
  containers:
  - name: container1
    image: tmkube/init
    volumeMounts:
    - name: emptyDir
      mountPath: /mount1
  - name: container2
    image: tmkube/init
    volumeMounts:
    - name: emptyDir
      mountPath: /mount2
  volumes:
  - name: emptyDir
    emptyDir: {}
