apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-3
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: container
    image: tmkube/init
    volumeMounts:
    - mountPath: /mount1
      name: host-path
  volumes:
  - name: host-path
    hostPath:
      path: /node-v
      type: DirectoryOrCreate
