apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-2
spec:
  containers:
  - name: container1
    image: tmkube/init
    volumeMounts:
    - mountPath: /mount1
      name: host-path
  - name: container2
    image: tmkube/init
    volumeMounts:
    - mountPath: /mount2
      name: host-path
  volumes:
  - name: host-path
    hostPath:
      path: /node-v
      type: DirectoryOrCreate
